version: '2'
services:
  margintrading:
    image: lykkex/margintrading
    container_name: margintrading
    environment:
      - SettingsUrl=${SettingsUrl}
      - KestrelThreadCount=${KestrelThreadCount}
      - IsLive=${IsLive}
      - AutoCreateAccounts=${AutoCreateAccounts}
    ports:
      - "5000:5000"
    networks:
      mynet:
        aliases:
          - margintrading

  mtaccounthistorybroker:
     image: lykkex/mtaccounthistorybroker
     container_name: mtaccounthistory
     environment:
       - SettingsUrl=${SettingsUrl}
     hostname: mtaccounthistory
     networks:
      mynet:
        aliases:
          - mtaccounthistory

  mtorderhistorybroker:
     image: lykkex/mtorderhistorybroker
     container_name: mtorderhistory
     environment:
       - SettingsUrl=${SettingsUrl}
     hostname: mtorderhistory
     networks:
      mynet:
        aliases:
          - mtorderhistory

  mtorderrejectedbroker:
     image: lykkex/mtorderrejectedbroker
     container_name: mtorderrejected
     environment:
       - SettingsUrl=${SettingsUrl}
     hostname: mtorderrejected
     networks:
      mynet:
        aliases:
          - mtorderrejected
  mttransactionbroker:
     image: lykkex/mttransactionbroker
     container_name: mttransactions
     environment:
       - SettingsUrl=${SettingsUrl}
     hostname: mttransactions
     networks:
      mynet:
        aliases:
          - mttransactions
  mtorderreportbroker:
     image: lykkex/mtorderreportbroker
     container_name: mtorderreport
     environment:
       - SettingsUrl=${SettingsUrl}
     hostname: mtorderreport
     networks:
      mynet:
        aliases:
          - mtorderreport
  mtriskmanagerbroker:
     image: lykkex/mtriskmanagerbroker
     container_name: mtriskmanager
     environment:
      - SettingsUrl=${SettingsUrl}
     hostname: mtriskmanager
     networks:
      mynet:
        aliases:
          - mtriskmanager
  mtpositionsbroker:
     image: lykkex/mtpositionsbroker
     container_name: mtpositions
     environment:
      - SettingsUrl=${SettingsUrl}
     hostname: mtpositions
     networks:
      mynet:
        aliases:
          - mtpositions
  mtpvarbroker:
     image: lykkex/mtpvarbroker
     container_name: mtpvar
     environment:
      - SettingsUrl=${SettingsUrl}
     hostname: mtpvar
     networks:
      mynet:
        aliases:
          - mtpvar
  mtivarbroker:
     image: lykkex/mtivarbroker
     container_name: mtivar
     environment:
      - SettingsUrl=${SettingsUrl}
     hostname: mtivar
     networks:
      mynet:
        aliases:
          - mtivar
networks:
  mynet:
    driver: bridge
