//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarginTrading.Backend.Core.Messages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MtMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MtMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MarginTrading.Backend.Core.Messages.MtMessages", typeof(MtMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccountAssetForTradingConditionNotFound {
            get {
                return ResourceManager.GetString("AccountAssetForTradingConditionNotFound", resourceCulture);
            }
        }
        
        public static string LeverageMaintanceIncorrect {
            get {
                return ResourceManager.GetString("LeverageMaintanceIncorrect", resourceCulture);
            }
        }
        
        public static string LeverageInitIncorrect {
            get {
                return ResourceManager.GetString("LeverageInitIncorrect", resourceCulture);
            }
        }
        
        public static string AccountByIdNotFound {
            get {
                return ResourceManager.GetString("AccountByIdNotFound", resourceCulture);
            }
        }
        
        public static string ClientIdNotFoundInCache {
            get {
                return ResourceManager.GetString("ClientIdNotFoundInCache", resourceCulture);
            }
        }
        
        public static string AccountNotFoundInCache {
            get {
                return ResourceManager.GetString("AccountNotFoundInCache", resourceCulture);
            }
        }
        
        public static string ClientHasAccountInCache {
            get {
                return ResourceManager.GetString("ClientHasAccountInCache", resourceCulture);
            }
        }
        
        public static string AccountGroupForTradingConditionNotFound {
            get {
                return ResourceManager.GetString("AccountGroupForTradingConditionNotFound", resourceCulture);
            }
        }
        
        public static string NotificationIdNotFound {
            get {
                return ResourceManager.GetString("NotificationIdNotFound", resourceCulture);
            }
        }
        
        public static string InstrumentNotFoundInCache {
            get {
                return ResourceManager.GetString("InstrumentNotFoundInCache", resourceCulture);
            }
        }
        
        public static string InstrumentWithAssetsNotFound {
            get {
                return ResourceManager.GetString("InstrumentWithAssetsNotFound", resourceCulture);
            }
        }
        
        public static string Notifications_MarginCall {
            get {
                return ResourceManager.GetString("Notifications_MarginCall", resourceCulture);
            }
        }
        
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        public static string CantRemoveOrderWithStatus {
            get {
                return ResourceManager.GetString("CantRemoveOrderWithStatus", resourceCulture);
            }
        }
        
        public static string CantGetOrderWithStatus {
            get {
                return ResourceManager.GetString("CantGetOrderWithStatus", resourceCulture);
            }
        }
        
        public static string QuoteNotFound {
            get {
                return ResourceManager.GetString("QuoteNotFound", resourceCulture);
            }
        }
        
        public static string FxRateNotFound {
            get {
                return ResourceManager.GetString("FxRateNotFound", resourceCulture);
            }
        }
        
        public static string Notifications_StopOutNotification {
            get {
                return ResourceManager.GetString("Notifications_StopOutNotification", resourceCulture);
            }
        }
        
        public static string Validation_PriceAboveAsk {
            get {
                return ResourceManager.GetString("Validation_PriceAboveAsk", resourceCulture);
            }
        }
        
        public static string Validation_PriceBelowBid {
            get {
                return ResourceManager.GetString("Validation_PriceBelowBid", resourceCulture);
            }
        }
        
        public static string Validation_NotEnoughBalance {
            get {
                return ResourceManager.GetString("Validation_NotEnoughBalance", resourceCulture);
            }
        }
        
        public static string Validation_TakeProfitMustBeMore {
            get {
                return ResourceManager.GetString("Validation_TakeProfitMustBeMore", resourceCulture);
            }
        }
        
        public static string Validation_StopLossMustBeLess {
            get {
                return ResourceManager.GetString("Validation_StopLossMustBeLess", resourceCulture);
            }
        }
        
        public static string Validation_TakeProfitMustBeLess {
            get {
                return ResourceManager.GetString("Validation_TakeProfitMustBeLess", resourceCulture);
            }
        }
        
        public static string Validation_StopLossMustBeMore {
            get {
                return ResourceManager.GetString("Validation_StopLossMustBeMore", resourceCulture);
            }
        }
        
        public static string Notifications_PendingOrderPlaced {
            get {
                return ResourceManager.GetString("Notifications_PendingOrderPlaced", resourceCulture);
            }
        }
        
        public static string Notifications_PendingOrderTriggered {
            get {
                return ResourceManager.GetString("Notifications_PendingOrderTriggered", resourceCulture);
            }
        }
        
        public static string Notifications_OrderPlaced {
            get {
                return ResourceManager.GetString("Notifications_OrderPlaced", resourceCulture);
            }
        }
        
        public static string Notifications_PendingOrderCanceled {
            get {
                return ResourceManager.GetString("Notifications_PendingOrderCanceled", resourceCulture);
            }
        }
        
        public static string Notifications_WithStopLossPhrase {
            get {
                return ResourceManager.GetString("Notifications_WithStopLossPhrase", resourceCulture);
            }
        }
        
        public static string Notifications_WithTakeProfitPhrase {
            get {
                return ResourceManager.GetString("Notifications_WithTakeProfitPhrase", resourceCulture);
            }
        }
        
        public static string Notifications_OrderClosed {
            get {
                return ResourceManager.GetString("Notifications_OrderClosed", resourceCulture);
            }
        }
    }
}
