//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace MarginTrading.Backend.Core.Messages {
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MtMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MtMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("MarginTrading.Backend.Core.Messages.MtMessages", typeof(MtMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t find AccountAsset for tradingConditionId: {0}, baseAssetId: {1}, instrument: {2}.
        /// </summary>
        public static string AccountAssetForTradingConditionNotFound {
            get {
                return ResourceManager.GetString("AccountAssetForTradingConditionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t get account by id = {0}.
        /// </summary>
        public static string AccountByIdNotFound {
            get {
                return ResourceManager.GetString("AccountByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t get AccountGroup for tradingConditionId = {0}, assetId = {1}.
        /// </summary>
        public static string AccountGroupForTradingConditionNotFound {
            get {
                return ResourceManager.GetString("AccountGroupForTradingConditionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot get order with id = {0} and status {1}.
        /// </summary>
        public static string CantGetOrderWithStatus {
            get {
                return ResourceManager.GetString("CantGetOrderWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot remove order with id = {0} and status {1}.
        /// </summary>
        public static string CantRemoveOrderWithStatus {
            get {
                return ResourceManager.GetString("CantRemoveOrderWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Client {0} doesn&apos;t have account {1} in the cache.
        /// </summary>
        public static string ClientAccountNotFoundInCache {
            get {
                return ResourceManager.GetString("ClientAccountNotFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Client {0} already has account {1} in the cache.
        /// </summary>
        public static string ClientHasAccountInCache {
            get {
                return ResourceManager.GetString("ClientHasAccountInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Client {0} doesn&apos;t exist in the cache.
        /// </summary>
        public static string ClientIdNotFoundInCache {
            get {
                return ResourceManager.GetString("ClientIdNotFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Instrument {0} does not exist in cache.
        /// </summary>
        public static string InstrumentNotFoundInCache {
            get {
                return ResourceManager.GetString("InstrumentNotFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There is no instrumet with assets {0} and {1}.
        /// </summary>
        public static string InstrumentWithAssetsNotFound {
            get {
                return ResourceManager.GetString("InstrumentWithAssetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LeverageInit &lt; 1 for tradingConditionId: {0}, baseAssetId: {1}, instrument: {2}.
        /// </summary>
        public static string LeverageInitIncorrect {
            get {
                return ResourceManager.GetString("LeverageInitIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LeverageMaintenance &lt; 1 for tradingConditionId: {0}, baseAssetId: {1}, instrument: {2}.
        /// </summary>
        public static string LeverageMaintanceIncorrect {
            get {
                return ResourceManager.GetString("LeverageMaintanceIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t get notification Id for clientId = {0}.
        /// </summary>
        public static string NotificationIdNotFound {
            get {
                return ResourceManager.GetString("NotificationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot get order with id = {0}.
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There is no quote for instrument {0}.
        /// </summary>
        public static string QuoteNotFound {
            get {
                return ResourceManager.GetString("QuoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not enough balance to open position.
        /// </summary>
        public static string Validation_NotEnoughBalance {
            get {
                return ResourceManager.GetString("Validation_NotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified price {0} is above current ask price {1}.
        /// </summary>
        public static string Validation_PriceAboveAsk {
            get {
                return ResourceManager.GetString("Validation_PriceAboveAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified price {0} is below current bid price {1}.
        /// </summary>
        public static string Validation_PriceBelowBid {
            get {
                return ResourceManager.GetString("Validation_PriceBelowBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified stop loss {0} must be less than {1}.
        /// </summary>
        public static string Validation_StopLossMustBeLess {
            get {
                return ResourceManager.GetString("Validation_StopLossMustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified stop loss {0} must be more than {1}.
        /// </summary>
        public static string Validation_StopLossMustBeMore {
            get {
                return ResourceManager.GetString("Validation_StopLossMustBeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified take profit {0} must be less than {1}.
        /// </summary>
        public static string Validation_TakeProfitMustBeLess {
            get {
                return ResourceManager.GetString("Validation_TakeProfitMustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified take profit {0} must be more than {1}.
        /// </summary>
        public static string Validation_TakeProfitMustBeMore {
            get {
                return ResourceManager.GetString("Validation_TakeProfitMustBeMore", resourceCulture);
            }
        }
    }
}
